tutorials/DockerComposeAsSystemdService.md

I thought this might be useful for somebody. This tutorial describes how you can setup multiple docker-compose services using a systemd service template. I hope this is somehow as you expect the tutorials to look like :)

Add tutorial about docker-compose services via systemd service templates

---

tutorials/ProsodyOnDebian.md

This is tutorial will guide you on how to install prosody in version trunk (aka master branch with nightly builds) on debian 9. At the bottom you can also find advanced stuff, for example usage behind a firewall or an IRC bridge.

Install and configure prosody on Debian (and extra features)

---

tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.en.md

As there are not enough default examples for IP addresses as mentioned in #34, I have used here
```
Client public IPv4: 78.47.166.55 (hetzner.com IPv4)
Client private IPv4: 192.168.0.10
```
in lines 28, 29 and 184-189
I have not found a complete tutorial online, this one is mixed from several tutorials and also contains own experiences. The installation and configuration routine is fully tested.

Install TURN/STUN server with coturn on Debian/Ubuntu

---

tutorials/howto-hcloud-cli/01.en.md

The Hetzner Cloud CLI Tutorial contained wrong metadata and a "not so good" title. This PR changes this.

Hetzner Cloud CLI - wrong title and metadata

---

tutorials/howto-hcloud-terraform/01.en.md

The Metadata for the Hetzner Cloud Terraform provider contained the description of the hcloud-cli Tutorial and it should contain the tag "Hetzner Cloud".

Hetzner Cloud Terraform Provider - wrong metadata

---

tutorials/cron-email-notifications/01.en.md

This tutorials explains how you an setup ssmtp to receive cron job logs via email. 
I have read and understood the Contributor's Certificate of Origin available at the end of https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md and I hereby certify that I meet the contribution criteria described in it. Signed-off-by: Timo 0mfhniozkb9s4q7e6ap8yvlt@nowitzki.me

Cronjob email reports via ssmtp

---

tutorial-template.md

I already noticed on some pull requests that people copy the template and than have `&lt;` tags in their tutorial. This pull request replaces them with proper `<`.

Replace XML/HTML tag in template.md

---

tutorials/prosody-on-debian9/01.en.md
tutorials/prosody-on-debian9/01.it.md

This PR fixes issues with the prosody on debian 9 tutorial:
1. When you copy the config file and run prosodyctl checkit will warn with
```
startup             warn        Configuration warning: /etc/prosody/prosody.cfg.lua:167: Duplicate option 'max_history_messages'
```
This PR Removes the first of the two duplicates
2. If you run the proposed command for adding the cronjob, it will overwrite all of your existing cronjobs. This PR implements directions to do it manually via crontab -e. The Italian translation of it was only done trough an online translation service, **somebody who is fluent in Italian probably should check this translation.**

Fix issues with Prosody on Debian 9

---

tutorials/install-and-configure-wireguard-vpn-debian/01.en.md

Signed-off-by: Ben G <bene.glvr@gmail.com>
Note: While the IP guidelines say use 10.0.0.1 as the public IP, this would be very misleading for this tutorial, where by default that is always the private VPN IP. 1.2.3.4 is used instead.

Installing and configuring a Wireguard VPN server on Debian 9.9

---

tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md

Due to various problems with the upload speed, this PR adds a description of "how to disable hardware checksum offload", which is the root cause for the bad upload.

pfSense Private Network Tutorial: Upload/Performance fix

---

tutorials/install-and-configure-ogp-agent-and-csgo-server-in-debian-ubuntu/01.en.md

This is a follow-up tutorial for my previous tutorial of the OGP Panel. This will explain to install Agent and link it to be used for any supported game servers.
Signed-off-by: Zishan Ansari <kinnngg786@gmail.com>

Install and configure Ogp Agent and run CSGO Server in Debian/Ubuntu

---

tutorials/basic-cloud-config/01.de.md
tutorials/basic-cloud-config/01.en.md

In Step 4.3 - Harden SSH the seed command to deactivate PasswordAuthentication does not work 
if the `sshd_config` option is present with a comment.
default state of sshd_conf in ubuntu 18.04
```
#PasswordAuthentication yes
#PermitEmptyPasswords no
```
The command below will not match `#PasswordAuthentication yes` 
```
- sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
```
I replaced it with an optional match `\(#\|\)`

Tutorial Basic Cloud Config: Fix sed command to match comments

---

tutorials/install-and-configure-proxmox_ve/01.de.md

In Zeile 47 den Hinweis für Debian 10 Proxmox VE 6.0 hinzugefügt

Debian 10 / Proxmox VE 6.0 Hinweis

---

tutorials/docker-compose-as-systemd-service/01.en.md
tutorials/docker-compose-as-systemd-service/01.ru.md

The docker image `v2tec/watchtower` is not maintained anymore, instead use
the currently maintained version `containrrr/watchtower`.
---
Signed-off-by: Bernd Stellwag <burned@zerties.org>

Update tutorial with maintained version of watchtover docker image

---

tutorials/a-basic-guide-to-php-symfony/01.en.md
tutorials/a-basic-guide-to-php-symfony/02.en.md

While reading the Symfony tutorial I found some typos and fixed them.
---
Signed-off-by: Bernd Stellwag <burned@zerties.org>

Fix some typos in the symfony tutorial

---

tutorials/howto-hcloud-kickstart-centos/01.en.md

I was following the tutorial but it was not clear at this point why the `hcloud_server_info` check is done. The existing explanation makes it seem that it is done to allow the following step to be skipped, but its value is never read.
Only after completing the full tutorial it becomes clear that this value is used later on, and the `hcloud_server` module is in fact not recreating an existing server.

Add further clarification on why there is an explicit check if the server exists

---

tutorials/basic-cloud-config/01.de.md
tutorials/basic-cloud-config/01.en.md

In Step 4.3 - Harden SSH the sed command for AuthorizedKeysFile does not work.
It fails with an error.
I escaped a slash which fixes this issue.

Fix sed command by escaping slash

---

tutorials/setup-nextjs-with-tailwind/01.en.md

There is an extra ` symbol, removed via this PR

remove excess `

---

tutorials/install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/01.en.md

Hello.
I found small issues with an existing tutorial.
Steps to reproduce:
1. Open https://community.hetzner.com/tutorials/install/install-encrypted-ubuntu-2004-with-automated-unlock-via-tang-and-clevis
2. Choose English in the language dropdown
3. Observe the 404 error

Fix the existing tutorial

---

tutorials/secure-ubuntu-server-with-ferm-firewall-and-fail2ban/01.en.md

The line removed from the tutorial will cause a server to be unable to boot correctly. Therefore this line should be removed quickly!

Update tutorial - remove wrong line

---

tutorials/install-and-configure-borgbackup/01.en.md

Side note: you have a couple of CRLF termination and you may want to normalize this.
See: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
```console
❯ file tutorials/*/* | grep CRLF
tutorials/configuring-windows-remote-desktop-services/01.de.md:                                UTF-8 Unicode text, with very long lines, with CRLF line terminators
tutorials/configuring-windows-remote-desktop-services/01.en.md:                                ASCII text, with very long lines, with CRLF line terminators
tutorials/cyberpanel-openlitespeed-mybb/01.en.md:                                              UTF-8 Unicode text, with very long lines, with CRLF line terminators
tutorials/howto-initial-setup-ubuntu/01.de.md: …
```

Fix typos (closes: #422)

---

tutorials/install-nomad-consul-cluster/01.en.md

the bin is installed to `/usr/local/bin` but the service config has `usr/bin`

fix incorrect path in consul service config

---

tutorials/how-to-install-archlinux-on-a-hetzner-cloud-server/01.en.md

There is now a `archlinux-bootstrap-x86_64.tar.gz` file on the mirrors.
Additionally:
* Fix Arch Linux name. See https://wiki.archlinux.org/title/Arch_terminology#Arch_Linux.
* Download the signature file from archlinux.org since getting it from the mirrors is not safe.
* The mirror.pkgbuild.com mirror is [not public](https://archlinux.org/mirrors/mirror.pkgbuild.com/), use geo.mirror.pkgbuild.com instead.
* Use keyserver.ubuntu.com since the sks keyserver pool is dead.

Use versionless bootstrap tarball in Arch Linux tutorial

---

tutorials/hcloud-install-rancher-single/01.en.md
tutorials/install-and-configure-routervm-for-vmware-vsphere/01.en.md
tutorials/install-and-configure-vmware-vsphere/01.en.md
tutorials/plesk-backup-storage-box/01.en.md
tutorials/prometheus-discovery/01.en.md
tutorials/proxmox-docker-zfs/01.en.md

Hetzner Robot URL has changed on the 21st September 2022
Old URL: https://robot.your-server.de/
New URL: https://robot.hetzner.com/
Source: https://status.hetzner.com/incident/1883187a-fe64-44ad-a3eb-25c6bab6e78c
This commit changes all 'robot.your-server.de' to 'robot.hetzner.com'.

Update Robot URL

---

tutorials/setup-mailserver-with-mailcow/01.en.md

This commit updates the tutorial to the current state (OS, Docker), removes a link to a malicious site and adds the topic Backups and enhances information about updates.
Also fixes #497.
Signed-off-by: kev-ac <oss@thiefes.de>

[Mailcow] Update to current state, remove malicious link and added new topics

---

tutorials/setup-mailserver-with-mailcow/01.ru.md

This PR removes one line, a link to "mailcow.farm" from the tutorial.
The link seems to be redirecting to some dodgy pages now.

[Mailcow] Remove malicious link from Russian version of tutorial

---

tutorials/install-and-configure-wireguard-vpn-debian/01.en.md
tutorials/install-and-secure-nginx-lets-encrypt-debian-10/01.en.md
tutorials/install-mattermost-on-managed-server/01.en.md
tutorials/install-nagios-core-on-managed-server/01.en.md
tutorials/install-windows/01.de.md
tutorials/install-windows/01.en.md
tutorials/linux-setup-gre-tunnel/01.en.md
tutorials/linux-setup-gre-tunnel/01.it.md

* ```` ```bash ```` or ```` ```shell ```` looks like this:
* ```` ```shellsession ```` looks like this:
Some text in the GitHub diff-viewer is highlighted with red background. This is because [install-mattermost-on-managed-server](https://github.com/hetzneronline/community-content/blob/d70b26f68d12d1cf5f5294540d0447da69dd8276/tutorials/install-mattermost-on-managed-server/01.en.md?plain=1#L88) contains invalid json in the code block.

fix formatting

---

tutorials/install-and-configure-borgbackup/01.de.md
tutorials/install-and-configure-borgbackup/01.en.md
tutorials/install-and-configure-borgbackup/01.ru.md

What changed:
* In the example bash scripts: I put variables that are used in BorgBackup commands in single quotes and exported them according to BorgBackup manual.

Resoves #636 /  Install and Configure BorgBackup -- Minor mistake in shell script variables

---

tutorials/install-and-configure-borgbackup/01.de.md
tutorials/install-and-configure-borgbackup/01.en.md

`borg prune` doesn't free disk space, so a user almost certainly wants to also run `borg compact` to free the disk space after a prune operation.

Add note about needing to run borg compact to free disk space

---

tutorials/install-and-configure-borgbackup/01.de.md
tutorials/install-and-configure-borgbackup/01.en.md
tutorials/install-and-configure-borgbackup/01.ru.md

In the example script, the `REPOSITORY` variable should be surrounded by double ticks `"` instead of single ones, since otherwise bash env substitution does not work.

use double quotes to fix bash env substitution

---

tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md

- The tutorial unfortunately did not / no longer work, and therefore had to be adapted, because wrong paths were configured for dropbear, so that it did not find the authorized keys.
- Dropbear calls a function in initramfs, which places a netplan config in /run/netplan, which in turn creates routes which are not necessary or even make hosts in the network unreachable. 
- Also it was not possible to log in with a normal RSA SSH key, and therefore it is necessary to add the parameter `-o "PubkeyAcceptedKeyTypes +ssh-rsa"`.
These problems are fixed with this merge request
Also smaller things were adapted.

Fixed installation of Ubuntu with full encryption

---

tutorials/install-and-configure-borgbackup/01.de.md
tutorials/install-and-configure-borgbackup/01.en.md

The old option was rather short and did not successfully explain what port to use. We should just point to the existing documentation that shows all options.

Point to storage box documentation ssh key in bogmatic tutorial

---

tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md

Add option for two drives
Fix #668

Update "How to install Ubuntu 20.04 with full disk encryption"

---

tutorials/freebsd-with-qemu-via-linux-rescue/01.en.md

Signed-off-by: Juergen Meier <jpm@jors.net>
My tutorial allows installation of FreeBSD without requiring a server with UEFI support as https://community.hetzner.com/tutorials/freebsd-openzfs-via-linux-rescue does.
I also noted that ZFS support in linux rescue disk seems to be broken in Helsinki DC. This method was tested in Falkenstein and Helsinki on older dedicated servers.

new tutorial: Installing freebsd with qemu via linux rescue (not needing UEFI)

---

tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.en.md
tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn/01.ru.md
tutorials/jitsi-meet-on-debian-ubuntu/01.en.md
tutorials/prosody-on-debian9/01.en.md
tutorials/prosody-on-debian9/01.it.md
tutorials/prosody-on-debian9/01.ru.md

Darft: Remove certbot-auto (deprecacted) from existing tutorials

---

tutorials/ai-chatbot-with-ollama-and-open-webui/01.de.md

There is a wrong spelling of Ollama in the German version.

Fix typo in ai-chatbot-with-ollama-and-open-webui/de

---

.gitattributes

Markdown files are [ignored by default](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#detectable) in the language stats, but for this repository it's a main language. This will include `*.md` files to the language stats. 

Show Markdown in the language stats

---

tutorials/install-shopware-6/01.en.md

- Updated PHP to 8.3
- Using Composer to create the project, is much easier than using web installer

shopware: update php and use composer instead of webinstaller

---

tutorials/deploy-nicegui/01.en.md

This is a correction to my NiceGUI tutorial. The accepted version had a hidden deficiency in the script `asgi.py`. Namely, the served page is the same across different machines, browsers or browser tabs. As a matter of fact, the usual way of serving pages in NiceGUI is by using the `@ui.page` decorator, similarly to other web frameworks. I think it is worth to correct this unfortunate oversight on my part. The little correction will improve user experience.

Correction to deploy nicegui

---

tutorials/cloudflare-website-protect/01.en.md

Use the suggested fix from the issue #832 to include v6 IPs.

Add IPv6 in "How to protect a website with Cloudflare without exposing ports to the Internet"

---

tutorials/how-to-install-archlinux-on-a-hetzner-cloud-server/01.en.md
tutorials/how-to-install-archlinux-on-a-hetzner-cloud-server/01.ru.md

Starting with the 2024.05.01 release, the Arch Linux bootstrap tarball uses zstd compression.
Related to https://gitlab.archlinux.org/archlinux/archiso/-/issues/130

tutorials/how-to-install-archlinux-on-a-hetzner-cloud-server: update bootstrap tarball extension

---

tutorials/testing-ansible-with-molecule/01.de.md
tutorials/testing-ansible-with-molecule/01.en.md

In this tutorial, we will unit test `ansible` with `molecule` framework on `Hetzner` infrastructure. 
Signed-off-by: [Harshavardhan Musanalli and email address [harshavmb@gmail.com](mailto:harshavmb@gmail.com)]

ansible testing with molecule

---

tutorials/install-lemp-stack-on-debian-12/01.en.md

Update Article for Debian 12 to keep it relevant.
Replaced the IP echoing services with https://ip.hetzner.com to make more use of Hetzner services.
Tracking issue #862

Update article for Debian 12

---

tutorials/install-and-configure-ntp/01.en.md
tutorials/install-and-configure-ntp/01.ru.md

This PR makes the english and russian variant of this article use the same command as the german version to install `ntp` on OpenSuSE.
Signed-off-by: Peter Lehmann <xgwq@xnee.net>

Make instructions match between languages

---

tutorials/install-caprover/01.en.md

📝 Change Docker installation steps in "Installing CapRover on Hetzner Cloud"

---

tutorials/how-to-set-up-nat-for-cloud-networks/01.de.md
tutorials/how-to-set-up-nat-for-cloud-networks/01.en.md

📝 Add Ubuntu 24.04 in "How to set up NAT gateway for private Cloud Networks"

---

tutorials/deploy-nodejs-with-docker/01.en.md

As dicussed in #932, here's the updated tutorial.
A couple of things to decide on:
- Whether the tutorial date should be change to today, or if there's an "updated at" field that could be used to signal that the tutorial is up-to-date.
- Whether the automated builds section should be removed or updated, since that Docker Hub feature is no longer free and requires a paid subscription.
> I have read and understood the Contributor's Certificate of Origin available at the end of 
> https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
> and I hereby certify that I meet the contribution criteria described in it.
> Signed-off-by: Matteo Contrini <matteo@contrini.it>

Update `deploy-nodejs-with-docker` tutorial

---

.github/workflows/check-annual-update.yml

* The table is sorted by path column.
* The path is clickable now.
* If the author doesn't have GitHub account `@` will not be present.
* The tutorials without an author will be always at the bottom.
You can run this script locally, but you need to run `rm summary-authors.md orphaned` after each run and provide `CURRENT_MONTH` variable.

Small adjustments to workflow script

---

tutorials/dockerizing-mariadb-with-alpine-linux/01.en.md
tutorials/dockerizing-mariadb-with-alpine-linux/02.en.md
tutorials/dockerizing-mariadb-with-alpine-linux/03.en.md

This tutorial is split into multiple parts.
1. Dockerizing MariaDB with Alpine Linux
2. Import and Export data in Dockerized MariaDB
3. Connect to Dockerized MariaDB with Node.js via Unix socket
> I have read and understood the Contributor's Certificate of Origin available at the end of 
> https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
> and I hereby certify that I meet the contribution criteria described in it.
> Signed-off-by: Reza Gharabaghi oqabemail@gmail.com

Dockerizing MariaDB with Alpine Linux

---

tutorials/deploy-static-site-offen-analytics/01.en.md

Update versions and install instructions to match what is available in late 2024
As requested in #957 
---
I tested this on a brand new Hetzner Cloud VPS which I created today. All versions are up to date.

Update deploy-static-site-offen tutorial

---

tutorials/how-to-install-archlinux-on-a-hetzner-cloud-server/01.en.md

Fix the genfstab command in "How to install Arch Linux on a Hetzner Cloud server"

---

tutorials/obfuscating-wireguard-using-wstunnel/01.en.md

* Add a note about Termux, as an alternative to TermOne Plus.
* Use a separate unprivileged user for the `wstunnel` systemd service.

Update "Obfuscating WireGuard using Wstunnel"

---

tutorials/install-kubernetes-cluster/01.en.md

Guide: https://community.hetzner.com/tutorials/install-kubernetes-cluster
Since the old k8s repository http://packages.cloud.google.com/apt/ has been deprecated on sep 13, 2023.
This means the guide no longer work and leaves the user with the following when trying to install the kubernetes packages:
```
Unable to locate package kubeadm
Unable to locate package kubectl
Unable to locate package kubelet
```
You can see the official kubernetes announcement regarding the deprecation, i have updated the guide to use the new repository pkgs.k8s.io
https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

Update kubernetes guide to work with the new pkgs.k8s.io repository

---

tutorials/nextcloud-hetzner-object-storage/01.en.md

Tutorial showing how to setup nextcloud using docker and the hetzner object storage as a back-end.
```
Signed-off-by: Silviu Vulcan https://github.com/filviu
```

nextcloud-object-storage

---

tutorials/custom-os-images-with-packer/01.de.md
tutorials/custom-os-images-with-packer/01.en.md

As requested in #1009 this updates the poss as a minimal changes was necessary.
It updates the hacloud-packer post to use a hcloud server type that is still avaiable for customers
Signed-off-by: Henrik Gerdes hegerdes@outlook.de

fix: update packer tutorial post

---

tutorials/game-server-factorio/01.en.md
tutorials/make-a-factorio-server/01.en.md

Signed-off-by: Jozef Mäsiar me@jopgamer.xyz

add make-a-factorio-server tutorial

---

tutorials/install-and-configure-proxmox_ve/01.de.md
tutorials/install-and-configure-proxmox_ve/01.en.md

This change updates the IPv6 network configuration for Proxmox VE hosts in a routed configuration.
Previously, the proposed configuration would create 3 /64 routes on the system.
- 1 route generated by the vmbr0 interface being a /64
- 1 route created manually with the `up ip -6 route add` for the same /64
- 1 route created by the eth0 interface being a /64 as well (wrongly so, because none of the /64 hosts will be reachable via NDP on the physical L2 to the router)
This change results in 2 routes: 
- a single /128 route to the hosts IPv6 address itself on eth0
- a single /64 route to the vmbr0 interface for the whole subnet
```
https://raw.githubusercontent.com/hetzneronline/community-content/maste …
```

 proxmox-ve: Fix IPv6 configuration in routed setup

---

tutorials/devops-recipe-using-ansible-to-build-a-web-server/01.en.md

Signed-off-by: Sergiu Chilat <chilatsergiu@gmail.com>

New tutorial:  How to setup a Nginx webserver using ansible on Ubuntu

---

tutorials/kubernetes-on-hetzner-using-bare-metal-servers/01.de.md
tutorials/kubernetes-on-hetzner-using-bare-metal-servers/01.en.md

I have read and understood the Contributor's Certificate of Origin available at the end of https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Lucas Rattz [lucasrattz999@gmail.com](mailto:lucasrattz999@gmail.com)

Kubernetes on Hetzner Using Bare Metal Servers as Nodes

---

tutorials/hetzner-object-storage-custom-domain/01.en.md

Tutorial shows how to setup custom domain with S3-compatible object storage using a reverse proxy.
At the time of writing this tutorial custom domain using CNAME is not available, and reverse proxy is the only way.
```
Signed-off-by: Ivan Zaitsev https://github.com/ivan-zaitsev
```

New tutorial - "Setup custom domain with S3-compatible object storage"

---

tutorials/restrict-access-by-ip-or-password-in-nginx/01.en.md

Replace python snippet with bash, which is more appropriate here. Works the same.

Update "Restrict access by an IP or password in nginx"

---

tutorials/kubernetes-on-hetzner-with-crio-flannel-and-hetzner-balancer/01.en.md
tutorials/kubernetes-on-hetzner-with-crio-flannel-and-hetzner-balancer/01.ru.md

Signed-off-by: Dmitry Tiunov d.y.tiunov@gmail.com

Kubernetes on hetzner with crio flannel and hetzner balancer

---

tutorials/deploy-django-with-nginx-and-s3-storage/01.en.md

Signed-off-by: Mohsen Nasiri [info@m0h53n.ir](mailto:info@m0h53n.ir)

✨ New tutorial - "Deploy Django with Nginx and S3 Storage"

---

tutorials/securing-ssh/01.de.md
tutorials/securing-ssh/01.en.md

I noticed a typo when I was working my way through the article "Securing the SSH service". The keyword `ClientActiveInterval` does not exist and appearantly got confused with the keyword [`ClientAliveInterval`](https://manpages.ubuntu.com/manpages/noble/en/man5/sshd_config.5.html#:~:text=disables%20connection%20termination.-,ClientAliveInterval,-Sets%20a%20timeout). I have therefore replaced it accordingly

Fixed typo in "Securing the SSH service"

---

tutorials/configuring-windows-remote-desktop-services/01.de.md
tutorials/configuring-windows-remote-desktop-services/01.en.md
tutorials/configuring-windows-remote-desktop-services/01.ru.md
tutorials/create-and-install-custom-centos-8-image/01.en.md
tutorials/howto-hcloud-terraform-fedora-coreos/01.en.md
tutorials/install-and-configure-vmware-vcenter/01.en.md
tutorials/install-and-secure-phpmyadmin-with-nginx-on-centos-7/01.en.md
tutorials/install-kubernetes-cluster/01.en.md
tutorials/install-outline-vpn-server/01.en.md
tutorials/lsi-raid-controller/01.ru.md
tutorials/setup-https-on-nginx-on-freebsd-12/01.en.md
tutorials/testing-ansible-with-molecule/01.de.md
tutorials/testing-ansible-with-molecule/01.en.md

I published my script that I used to find the broken links:
https://github.com/wpdevelopment11/brittle
I will publish another script that I used to extract links from Markdown files soon.

Fix broken links

---

tutorials/encrypting-your-files-in-the-cloud-using-securefs/01.en.md

Update "Encrypting your files in the cloud using securefs"

---

tutorials/hyperconverged-proxmox-cloud/01.en.md

Small changes in "Setting up your own public cloud with Proxmox on Hetzner bare metal"

---

tutorials/how-to-install-nginx-on-ubuntu-20-04/01.en.md

Add command in "How to install Nginx on Ubuntu 20.04"

---

tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md

Add note to deactivate hc-utils, when using netplan.

Update "How to route cloud server over private network using pfSense and Hetzner Cloud Networks"

---

tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md

Fix typo in "How to install Ubuntu 24.04 with full disk encryption"

---

tutorials/freebsd-with-openzfs-via-linux-rescue/01.en.md

Update links in "Installing FreeBSD with OpenZFS via the Linux rescue system"
