hetzneronline/community-content

tutorials/hcloud-howto-cli.md
tutorials/howto-hcloud-cli/01.en.md

We plan to add a hcloud-cli tutorial for the start.

Add hcloud-cli Tutorial

---

tutorials/install-public-ntp-server-on-debian-ubuntu/01.en.md

Install public NTP server and optionally add it to the NTP pool

---

tutorials/prosody-on-debian9/01.en.md

Please merge as fast as possible.

Change to correct domain

---

tutorials/install-lamp-server-on-centos-7/01.en.md

push tutorial lamp centos 7

---

tutorials/setup-mailserver-with-mailcow/01.en.md

I wrote a new article on how to setup your own mail server with Mailcow :)
Signed-off-by: Timo 0mfhniozkb9s4q7e6ap8yvlt@nowitzki.me

Setup a mail server with Mailcow

---

tutorials/install-teamspeak3-server/01.de.md
tutorials/install-teamspeak3-server/01.en.md

Signed-off-by: Markus markus@omg-network.de

How to install Teamspeak 3 server software on Windows & Linux systems [DE/EN]

---

README.md

Extend README.md to guide to the Hetzner Forum or the Community-Content Issues for guidance as where to place requests for specific tutorials, request changes, and/or advice.
Signed-off-by: Thomas Blank blanky0230@gmail.com

Add section about 'requesting' of content / help.

---

tutorials/deploy-laravel-on-hetzner-cloud/01.en.md

I suppose the author meant to write "If" instead of "iL" :)

fix minor typo.

---

tutorials/howto-enable-igpu/01.de.md
tutorials/howto-enable-igpu/01.en.md

Signed-off-by: Markus markus@omg-network.de

How to enable the integrated iGPU for Intel CPUs

---

tutorials/game-server-with-amp/01.en.md

Tutorial on how to setup a Game server with AMP from Qubecoders.
Signed-off-by: Timo 0mfhniozkb9s4q7e6ap8yvlt@nowitzki.me

Created tutorial on how to setup a game server with AMP

---

tutorials/setup-monitoring-for-managedserver-based-on-monitoringplugins/01.en.md
tutorials/setup-monitoring-on-managed-server/01.en.md

Signed-off-by: Alexander Knerlein <alexanderknerlein@outlook.de>

Setup monitoring for Managed Server based on the Monitoring Plugins

---

tutorials/secure-tmp-folder/01.en.md

Signed-off-by: Daniel McDonald - mail@danielmcdonald.de

Securing tmp Folder of Webserver

---

tutorials/install-solusvm-with-openvz-and-kvm-nodes/01.en.md

Signed-off-by:
Ahmed Gad eng.ahmedmgad@gmail.com

add Install SolusVM with OpenVZ and KVM nodes tutorial

---

tutorial-template.md

Closes #34 
As this is a fundamental and permanent change, several people should approve before merging.

Add missing default IP addresses

---

tutorials/ProsodyOnDebian-IT.md
tutorials/prosody-on-debian9/01.it.md

Hi
I translated this [guide](https://github.com/hetzneronline/community-content/pull/3/commits/228c0d4fdd38cc85c3c9742f727c2ed115079f2f) in italian.
Signed-off-by: <Massimiliano massimiliano@disroot.org>

Italian Translation

---

tutorials/install-gameserver-csgo/01.de.md
tutorials/install-gameserver-csgo/01.en.md
tutorials/install-steamcmd/01.de.md
tutorials/install-steamcmd/01.en.md

Signed-off-by: Markus markus@omg-network.de

Install SteamCMD [DE/EN] & Install CSGO Game Server [DE/EN]

---

tutorials/how-to-reset-mysql-or-mariadb-root-password/01.en.md

Signed-off-by: Amin Khoshnood <noodi.net@gmail.com>

How to Reset MySQL or MariaDB Root Password

---

tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-centos-7/01.en.md

How To Install Linux, Nginx, MySQL, PHP (LEMP) stack On CentOS 7

---

tutorials/a-basic-guide-to-php-symfony/01.en.md
tutorials/a-basic-guide-to-php-symfony/02.en.md

This is a somewhat simple introduction to PHP Symfony. Please not that this is till pretty much work in progress.
Signed-off-by: Moritz Fromm <git@moritz-fromm.de>

Add A basic guide to PHP Symfony

---

tutorials/howto-securing-ssh/01.de.md
tutorials/howto-securing-ssh/01.en.md

Signed-off-by: Markus markus@omg-network.de

How to securing SSH on Linux systems [DE/EN]

---

tutorials/how-to-install-nagios-on-centos-7/01.en.md
tutorials/install-nagios-on-centos-7/01.en.md

How to Install Nagios 4.4.3 on CentOS 7

---

tutorials/install-and-configure-danted-proxy-socks5/01.en.md

Signed-off-by: [Juni Yadi <juniyadi@protonmail.com>]

Add Tutorial Danted Socks5 Proxy

---

tutorials/howto-hcloud-ansible/01.en.md

Already reviewed (here: https://github.com/LKaemmerling/community-content/pull/1)
Please wait for a "go" from my side before merging this. We would need also a deployment after this.

Hcloud Ansible

---

tutorials/add-sftp-only-user-no-ssh-access-on-centos-7/01.en.md
tutorials/enable-sftp-without-shell-access-on-centos-7/01.en.md

How To Enable SFTP Without Shell Access on CentOS 7

---

tutorials/howto-setup-mdadm/01.de.md
tutorials/howto-setup-mdadm/01.en.md

Signed-off-by: markus@omg-network.de

How to setup mdadm Software RAID

---

tutorials/configure-mariadb-master-slave-replication-on-centos-7/01.en.md

How to Configure MySQL Master-Slave Replication on CentOS 7

---

tutorials/setup-a-firewall-with-ipfw-on-freebsd-12/01.en.md

Signed-off-by: youiopmop rosethorn@riseup.net

Add "Setup a Firewall with IPFW on FreeBSD 12"

---

tutorials/setup-a-tor-relay-on-freebsd-12/01.en.md

Signed-off-by: youiopmop rosethorn@riseup.net

Add "Setup a Tor Relay on FreeBSD 12"

---

tutorials/nvidia-drivers-on-ubuntu/01.en.md
tutorials/nvidia-drivers/01.en.md

This tutorial describes how you can install the nvidia driver on a server with a Nvidia GPU

Nividia drivers on Ubuntu

---

tutorials/install-nginx-with-brotli-and-gzip-compression-on-ubuntu/01.en.md

Signed-off-by: [Martin Sholev sholev.martins@gmail.com]

Installing NGINX with Brotli and Gzip compression on Ubuntu

---

tutorials/install-lemp-stack-on-debian-10/01.en.md

Install LEMP Stack on Debian 10

---

tutorials/secure-nginx-with-let-s-encrypt-on-centos-7/01.en.md

How to Secure Nginx with Let's Encrypt on CentOS 7

---

tutorials/secure-nginx-with-let-s-encrypt-on-debian-10/01.en.md
tutorials/secure-nginx-with-lets-encrypt-on-debian-10/01.en.md

How to Secure Nginx with Let's Encrypt on Debian 10

---

tutorials/how-to-install-r-on-debian-10/01.en.md

Signed-off-by: Roland Balla <balla.roland96@gmail.com>

How To Install R on Debian 10

---

tutorials/linux-setup-gre-tunnel/01.en.md

Signed-off-by: Fabrizio La Rosa lr.fabrizio@gmail.com

Linux setup GRE tunnel

---

tutorials/how-to-install-git-on-ubuntu-18.04/01.en.md

Signed-off-by: Roland Balla <balla.roland96@gmail.com>

How To Install Git on Ubuntu 18.04

---

tutorials/debian-buster-docker-install-dualstack-ipv6nat-firewall/01.en.md

Signed-off-by: Elias Werberich <elias@werberich.de>

Tutorial: Install Docker CE on Debian Buster with Dualstack IPv6-NAT and Firewall Support

---

tutorials/linux-setup-gre-tunnel/01.en.md
tutorials/linux-setup-gre-tunnel/01.it.md

Signed-off-by: Fabrizio La Rosa lr.fabrizio@gmail.com

Translation (IT): Linux setup tunnel GRE

---

tutorials/debian-buster-docker-install-dualstack-ipv6nat-firewall/01.en.md
tutorials/linux-setup-gre-tunnel/01.en.md
tutorials/linux-setup-gre-tunnel/01.it.md

Gre tutorial italian update

---

tutorials/gnu-stow/01.en.md
tutorials/using-gnu-stow-to-manage-manually-compiled-software/01.en.md

Signed-off-by: Richard <nyuszika7h@gmail.com>

New tutorial: Using GNU stow to manage manually compiled software

---

tutorials/install-kubernetes-cluster/01.en.md

This is a guide on how to install kubernetes on a set of Hetzner Cloud servers. The guide is not yet finished, but wanted to already create a PR to get further feedback.
Currently open points:
* Further explanations to how and why LoadBalancing works
* Recheck grammar etc
Signed-off-by: Christian Beneke <c.beneke@wirelab.org>

Kubernetes installation guide

---

tutorials/create-and-install-custom-centos-8-image/01.en.md

Signed-off-by: Yuri Moens <yuri.moens@gmail.com>

Add "Create and install custom CentOS 8 image" tutorial

---

tutorials/real-time-apps-with-go-and-reactjs/01.en.md
tutorials/real-time-apps-with-go-and-reactjs/02.en.md
tutorials/real-time-apps-with-go-and-reactjs/03.en.md

Signed-off-by: Thomas Schäfer github@tschaefer.eu

add real-time-apps-with-go-and-reactjs part 3

---

tutorials/install-a-femp-stack-on-freebsd-12/01.en.md

Updated to use the newest PHP version available for FreeBSD 12

Updating FreeBSD 12 FEMP stack tutorial for latest php version

---

tutorials/linux-setup-gre-tunnel/01.en.md

I have fixed some grammar in the titles that sounded awkward and solved the caps on every word that is simply disgusting.
Regards
Alberto

Fixed titles grammar and "Camelish" caps

---

tutorials/install-and-configure-ogp-panel-in-debian-ubuntu/01.en.md

Signed-off-by: Zishan Ansari kinnngg786@gmail.com

Tutorial for Install & Configure of Open Game Panel in Debian or Ubuntu

---

tutorials/create-microk8s-cluster/01.en.md

Hi, I've created a new tutorial for installing Microk8s into Hetzner Cloud. 
Signed-off-by: Rob Ericsson <rob@l10systems.com>

Microk8s tutorial

---

tutorials/how-to-mine-monero-on-freebsd-12/01.en.md

Signed-off-by: youiopmop rosethorn@riseup.net

Add tutorial 'How to mine Monero on FreeBSD 12'

---

tutorials/howto-hcloud-kickstart-centos/01.en.md

Signed-off-by: Jeroen Hoekx <jeroen@hoekx.be>

Add how-to 'Kickstart a CentOS server on Hetzner Cloud with Ansible'

---

tutorials/howto-highly-available-load-balancer-hetzner-cloud-ansible/01.en.md

Hi! This is my first contribution to the community so I hope it's OK. It's a tutorial on setting up HA load balancers - since HC doesn't offer this service yet :) - that serves as an introduction to Ansible at the same time. Looking forward to feedback!
Signed-off-by: Vito Botta vito@botta.me

Add How-to: Provisioning a highly available load balancer in Hetzner Cloud with Ansible

---

tutorials/install-and-secure-nginx-lets-encrypt-debian-10/01.en.md

Signed-off-by: David Masteritx <8766@protonmail.com>

Install and Secure Nginx with Let's Encrypt in Debian 10

---

tutorials/letsencrypt-dns/01.en.md

Signed-off-by: Dominik Schoeffmann, dominik_schoeffmann@posteo.net

add letsencrypt dns tutorial

---

tutorials/block-outgoing-traffic-to-private-networks/01.en.md

Signed-off-by: Dashamir Hoxha <dashohoxha@gmail.com>

Tutorial: Block Outgoing Traffic to Private Networks

---

README.md

Added link to Test Suite

---

tutorials/install-gameserver-csgo/01.de.md
tutorials/install-gameserver-csgo/01.fi.md

Signed-off-by: Kimmo Tamio kimmo@kimmotamio.fi

Translation (FI): Installing a CSGO game server

---

tutorials/openssh-with-u2f-security-key-debian-10/01.en.md

Signed-off-by: Erisa A <seriel@erisa.moe>

Add tutorial "Building OpenSSH to work with U2F Security Keys on Debian 10 (Buster)"

---

tutorials/install-tigervnc/01.de.md
tutorials/install-tigervnc/01.en.md

This tutorial explains how to install tigervnc on ubuntu.
LEGAL:
Signed-off-by: Friedrich Lucas <friedrichlucas.99@gmail.com>

How To install TigerVNC Tutorial

---

tutorials/setup-monitoring-on-managed-server/01.en.md
tutorials/setup-monitoring-on-managed-server/01.ru.md
tutorials/setup-squid-with-cache-antivirus-and-ssl-mitm-mode-on-managed-server/01.en.md

I have updated the tutorials setup-monitoring-on-managed-server and setup-squid-with-cache-antivirus-and-ssl-mitm-mode-on-managed-server

Update formatting grammar and more

---

tutorials/howto-hcloud-terraform-fedora-coreos/01.en.md

Signed-off-by: Patrick Remy <github@patrick-remy.dev>

Add tutorial "Install Fedora CoreOS at Hetzner Cloud"

---

tutorials/howto-hcloud-terraform-fedora-coreos/01.en.md

See https://github.com/hetzneronline/community-content/pull/271#issuecomment-788983860

Adjust signed email address at Fedora CoreOS tutorial

---

tutorials/connect-avm-fritzbox-to-pfsense-ipsec/01.en.md

Signed-off-by: Markus Hupfauer markus@hupfauer.one
---
Thanks for the excellent spellchecking and rewriting of some sentences.
The improvement changed the URL string of the AVM DynDNS Update URL. This change will break the configuration and therefore needs to be reverted back.
@leojakeson @rook59

Fixed issue with english spellcheck.

---

tutorials/setup-autofs-mount-storagebox/01.en.md

Signed-off-by: Dirk Jugov <dirk@jugov.de>

Tutorial autofs storagebox

---

tutorials/install-and-configure-proxmox_ve/01.de.md
tutorials/install-and-configure-proxmox_ve/01.en.md

+ updated for Debian 10
+ changed misleading explanations 
+ added ssh security article
+ minor changes / fixed typos
Signed-off-by: Dirk Vetter dv@fastmail.de

Updated Proxmox Article for Debian 10 ger/eng

---

tutorials/setup-ssh-chroot-jail/01.en.md

* Create tutorial in English version on how to setup a SSH chroot jail

Add tutorial setup SSH chroot jail

---

tutorials/install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/01.en.md

Signed-off-by: Philipp Roth <philipp.roth@hetzner.com>

add install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/

---

tutorials/how-to-install-freebsd-on-dedicated-root-servers/01.de.md
tutorials/how-to-install-freebsd-on-dedicated-root-servers/01.en.md

Signed-off-by: Marcel Deglau marcel.deglau@hetzner.com

Updated: How to install FreeBSD on Dedicated Root Servers

---

tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md

Signed-off-by: Philipp Roth <philipp.roth@hetzner.com>

Add german translation for installing ubuntu 2004 with FDE

---

tutorials/simple-firewall-management-with-ufw/01.de.md
tutorials/simple-firewall-management-with-ufw/01.en.md

Signed-off-by: Marcel Deglau marcel.deglau@hetzner.com

Added: Simple Firewall Management with UFW

---

tutorials/configure-lb-cert-with-external-domain/01.en.md

I copied that url from the german translation

Image link broken

---

tutorials/awx-without-kubernetes/01.en.md

I have read and understood the Contributor's Certificate of Origin available at the end of https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Markus Kostrzewski <ciapa@ciapa.tech>

Add tutorial for AWX without Kubernetes

---

tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md

Signed-off-by: Helmer Barcos helmer@barcos.co

Adding Tutorial: Migration from CVS to Git

---

tutorials/simple-spa-version-notifier/01.de.md
tutorials/simple-spa-version-notifier/01.en.md

Signed-off-by: Thomas Schäfer <t.schaefer@headtrip.eu>

Add tutorial simple-spa-version-notifier

---

tutorials/setup-ubuntu-20-04/01.en.md

Signed-off-by: Johannes Pirmann johannes.pirmann@gmail.com

Initial Ubuntu 20.04 server setup

---

tutorials/install-and-configure-proxmox_ve/01.de.md
tutorials/install-and-configure-proxmox_ve/01.en.md
tutorials/install-and-configure-proxmox_ve/01.ru.md

added hwaddress for bridged setup in proxmox 7

update for proxmox 7

---

tutorials/install-nomad-consul-cluster/01.en.md

Signed-off-by: Dominik Langer <hdommme@gmail.com>

Add tutorial: Install a Nomad cluster with Consul on cloud servers

---

tutorials/cockroachdb-cluster-on-hetzner-cloud/01.en.md

Signed-off-by: https://github.com/egoisticalgiraffe

add tutorials/cockroachdb-cluster-on-hetzner-cloud

---

tutorials/secure-ubuntu-server-with-ferm-firewall-and-fail2ban/01.en.md

Signed-off-by: Maximilian Schumacher <max.schumacher96@icloud.com>

New Ferm fail2ban article

---

tutorials/proxmox-on-cloud/01.en.md

Signed-off-by: Stefan Kachlyr <stefan@kachlyr.at>

Proxmox on Hetzner Cloud

---

tutorials/howto-hcloud-ansible/01.en.md

Current link no longer exists with latest doc version.

Update documentation link

---

tutorials/caddy-as-simple-reverse-proxy-and-file-server/01.en.md

Signed-off-by: Maximilian Jannack maxijannack@t-online.de

Added tutorial for setting up Caddy with basic examples

---

tutorials/install-and-configure-borgmatic/01.en.md

Two simple small changes, to ensure proper readability and understanding of the [borgmatic article](https://community.hetzner.com/tutorials/install-and-configure-borgmatic/).
Signed-off-by: Jason N. <githubjn@nabein.me>

Update - Add missing text to borgmatic backup tutorial

---

tutorials/postfix-as-SMTP-relay-server/01.en.md

Signed-off-by: Esmail EL BoB <esmail@esmailelbob.xyz>

Setup postfix as outbound SMTP relay server

---

tutorials/make-a-minecraft-server/01.en.md

Signed-off-by: Yusuf Yaser [me@yusufyaser.xyz](mailto:me@yusufyaser.xyz)

Add tutorial - How to make a Minecraft server

---

tutorials/run-docker-containers-on-a-managed-server-with-udocker/01.en.md

Signed-off-by: Alexander Knerlein [alexanderknerlein@outlook.de](mailto:alexanderknerlein@outlook.de)

 Add tutorial - Run Docker containers on a Managed Server with udocker

---

tutorials/how-to-install-archlinux-on-a-hetzner-cloud-server/01.en.md

Signed-off-by: Patrick Michl <huanzodev@gmail.com>

Add Tutorial: How to install Archlinux on a Hetzner Cloud server

---

tutorials/add-ssh-key-to-your-hetzner-cloud/01.en.md

Fixes #408 
- Added description on how to add SSH key to existing server
- some small changes (Removed the need for 1 application which is not included in all repositories and would add unnecessary complexity)

Added ssh key as afterthought and details

---

tutorials/setup-mailserver-with-mailcow/01.en.md

Fixes #411 
- Added information regarding firewall
- Updated OS
- Compressed step count by combining similar and easy steps to 1 section

Added notes and compressed step count

---

tutorials/install-shlink-docker/01.de.md
tutorials/install-shlink-docker/01.en.md

Signed-off-by: Lars Hubrich <git@lars-hubrich.de>

Add tutorial - Installation guide for Shlink as a Docker Container

---

tutorials/docker-ipv6-securely/01.en.md

Thanks for the article!
I saw few typos which corrected

Couple of typos in "IPv6 on Docker securely"

---

tutorials/install-debian-11-with-lvm-encrypted-nvme-software-raid/01.en.md

Signed-off-by: Christian Külker <hetzner-community-content@c8i.org>

Install Debian 11 with LVM encrypted NVMe software RAID

---

tutorials/install-and-configure-borgbackup/01.de.md
tutorials/install-and-configure-borgbackup/01.en.md

Remove Borg 1.0 as it was removed from the Storage Boxes.

Remove borg 1.0

---

tutorials/how-to-reset-mysql-or-mariadb-root-password/01.en.md

Major changes:
* add note about "Directory '/var/run/mysqld' for UNIX socket file don't exists" error message
Minor changes:
* replace inline code with code blocks when needed
* start each sentence from a line
* typo fixes

Proofreading How to Reset MySQL or MariaDB Root Password

---

tutorials/install-windows/01.de.md
tutorials/install-windows/01.en.md

Installing Windows without KVM

---

tutorials/raid-repartitioning-on-running-system/01.en.md
tutorials/raid-repartitioning-on-system-in-use/01.de.md
tutorials/raid-repartitioning-on-system-in-use/01.en.md

Signed-off-by: Andreas Wahlen <andreaswahlen@unitybox.de>

Added tutorial raid-repartitioning-on-system-in-use

---

tutorials/install-and-secure-nginx-lets-encrypt-debian-10/01.en.md

[Install and Secure Nginx with Let’s Encrypt in Debian 10](https://community.hetzner.com/tutorials/install-and-secure-nginx-lets-encrypt-debian-10)
Reproduced on Debian 10.
Only minor changes:
* add `-v` option to `mkdir` and `ln` commands
* fix heading styling
* get rid of sudo
* highlight words
* paraphrases
* remove reference to external service ifconfig.co
* split long paragraphs for editing and diffing purposes
* typo fixes
* update output of `certbot run` and `systemctl status` commands
* use all lowercase for `nginx` (source: https://nginx.org/en/)

Proofreading Install and Secure Nginx with Let’s Encrypt in Debian 10

---

tutorials/awx-without-kubernetes/01.en.md

Reproduced on Ubuntu 20.04
Major changes:
* add description for options of `useradd` and `git switch` commands
* add domain name into Requirements section
* add missing Debian packages
* add note about inotify watches
* restructure tutorial
* update AWX version
* update link to ansible documentation
Minor changes:
* fix heading styling
* fix languages for code blocks
* paraphrases
* reformat table
* remove `-y` option in `apt` commands
* split long paragraphs
* typo fixes

Proofreading Install and Configure AWX without Using Kubernetes

---

tutorials/howto-initial-setup-ubuntu/01.de.md
tutorials/howto-initial-setup-ubuntu/01.en.md

Existing tutorial: fix mistake in the description of step 1

---

tutorials/how-to-install-nginx-on-ubuntu-20-04/01.en.md

Signed-off-by: wpdevelopment11@gmail.com

Existing tutorial: fixes

---

tutorials/create-a-client-server-for-your-private-network-using-cloud-config/01.en.md
tutorials/create-client-for-pvt-net-using-cloud-config/01.en.md

Signed-off-by: riwin <riwin-github@web.de>

Create a client server for your private network using cloud-config

---

tutorials/restrict-access-by-ip-or-password-in-nginx/01.en.md
tutorials/the-access-restriction-by-an-ip-and-password-in-nginx-on-ubuntu/01.en.md

New tutorial: The access restriction by an IP and password in nginx on Ubuntu

---

tutorials/install-and-configure-prometheus-stack/01.de.md
tutorials/install-and-configure-prometheus-stack/01.en.md
tutorials/install-and-configure-prometheus-stack/01.ru.md

Installation and configuration of the Prometheus Metrics stack

Added Russian translation of article

---

tutorials/proxmox-docker-zfs/01.en.md

Update "Installing Proxmox and Docker on ZFS"

---

tutorials/setup-mailserver-with-mailcow/01.en.md

Update "Set up your own mail server with Mailcow"

---

tutorials/basic-cloud-config/01.de.md
tutorials/basic-cloud-config/01.en.md

Update "Basic Cloud Config"

---

tutorials/setup-https-on-nginx-on-freebsd-12/01.en.md

Found with ```` ```$(?!\n\n) ```` in vscode.

add language to code blocks

---

tutorials/install-kubernetes-cluster/01.en.md

Update "Install a Kubernetes cluster on cloud servers"

---

tutorials/block-outgoing-traffic-to-private-networks/01.en.md

Update "Block Outgoing Traffic to Private Networks"

---

tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md

Update pfSense tutorial
Fix #466

Update "How to route cloud server over private network using pfSense and Hetzner Cloud Networks"

---

tutorials/install-and-configure-borgmatic/01.en.md

Update "Install and configure borgmatic"

---

tutorials/install-and-configure-vmware-vsphere/01.en.md

Update "Install and configure VMware vSphere"

---

tutorials/how-to-install-SmartOS/01.en.md

Adapt the approach of the installation to changes in the SmartOS Setup (wizard) on recent SmartOS versions.

adapt to installation of newer SmartOS versions

---

tutorials/install-debian-11-with-lvm-encrypted-nvme-software-raid/01.en.md

Update image in "Encrypted Debian 11 on a NVMe software RAID"

---

tutorials/how-to-set-up-nat-for-cloud-networks/01.de.md
tutorials/how-to-set-up-nat-for-cloud-networks/01.en.md

Update "NAT gateway for private Cloud Networks"

---

tutorials/install-debian-11-with-lvm-encrypted-nvme-software-raid/01.en.md
tutorials/verdaccio-secure-fedora-server/01.en.md

Signed-off-by: Barnabas Bucsy <barnabas.bucsy@gmail.com>

Tutorial: Verdaccio Private Node.js Registry

---

tutorials/install-caprover/01.en.md

Hi Hetzner Team,
When setting up CapRover on my new Hetzner instance I noticed that the current docs about installing CapRover on Hetzner Cloud are a bit out of date. After successfully installing and running CapRover on my new instance, I am submitting a PR for updating the docs to be more current with how CapRover is installed and ran.
Please let me know any feedbacks you may have.
Thanks

Updated CapRover <> Hetzner Docs

---

tutorials/mount-volume-on-multiple-servers-with-sshfs/01.en.md

Update "Mount volume on multiple servers"

---

tutorials/install-lemp-stack-on-ubuntu-20.04/01.en.md

Update "How to install a LEMP Stack on Ubuntu 20.04 LTS"

---

tutorials/install-windows/01.de.md
tutorials/install-windows/01.en.md

Fix #666 
Replace "/dev/sdb" with "/dev/sda"

Updade "Installing Windows without KVM"

---

tutorials/make-a-minecraft-server/01.en.md

Update "How to create a Minecraft server on a VPS"

---

tutorials/deploy-github-artifacts-to-storagebox/01.en.md

Signed-off-by: Harshavardhan Musanalli - [harshavmb@gmail.com](mailto:harshavmb@gmail.com)

Tutorial for deploying GitHub artifact to Hetzner storage box

---

tutorials/a-basic-guide-to-php-symfony/01.en.md
tutorials/a-basic-guide-to-php-symfony/02.en.md
tutorials/cockroachdb-cluster-on-hetzner-cloud/01.en.md
tutorials/install-and-configure-puppet-master-and-agent/01.de.md
tutorials/install-and-configure-puppet-master-and-agent/01.en.md
tutorials/install-archlinux-using-archinstall/01.en.md
tutorials/install-lemp-stack-on-debian-10/01.en.md
tutorials/install-livck/01.en.md
tutorials/install-matomo-analytics-on-centos-7/01.en.md
tutorials/install-plesk-cloud-server/01.en.md
tutorials/install-sinusbot/01.de.md
tutorials/migrate-to-hetzner-web-hosting/01.de.md
tutorials/mikrotik-chr-basic-setup/01.en.md
tutorials/mikrotik-chr-basic-setup/01.ru.md
tutorials/prosody-on-debian9/01.en.md
tutorials/prosody-on-debian9/01.it.md
tutorials/prosody-on-debian9/01.ru.md
tutorials/real-time-apps-with-go-and-reactjs/03.en.md
tutorials/secure-fedora-webserver/01.en.md
tutorials/securing-ssh/01.de.md
tutorials/securing-ssh/01.en.md
tutorials/setup-monitoring-on-managed-server/01.en.md

Fix code blocks

---

tutorials/proxmox-prometheus-exporter/01.en.md

Update "Gather metrics of your Proxmox VE server with Prometheus"

---

tutorials/install-and-configure-x2goserver/01.de.md
tutorials/install-and-configure-x2goserver/01.en.md

Remove wrong language (`ru`) from metadata

Update "Install and Configure Ubuntu Remote Desktop with XFCE using X2Go"

---

tutorials/howto-setup-mdadm/01.de.md
tutorials/howto-setup-mdadm/01.en.md

Update "Software RAID under Linux"

---

tutorials/kubernetes-with-claudie/01.en.md

Signed-off-by: cloudziu adam.stawski@berops.com

New tutorial - Kubernetes in Hetzner with Claudie!

---

tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md

Add note in "How to route cloud server using pfSense and Hetzner Cloud Networks"

---

tutorials/mikrotik-chr-basic-setup/01.en.md
tutorials/mikrotik-chr-basic-setup/01.ru.md

Update ""How to install MikroTik CHR on Hetzner Cloud""

---

tutorials/configure-cloud-ha-keepalived/01.de.md
tutorials/configure-cloud-ha-keepalived/01.en.md

Update "Implementation of a Cloud HA infrastructure with Keepalived"

---

contributing.de.md
contributing.md

Update links in the contribution guidelines

---

tutorials/proxmox-prometheus-exporter/01.en.md

Fixed the issue #742 submitted by myself.

fixed issue #742 01.en.md

---

tutorials/installing-wordpress-on-ubuntu/01.en.md

Update "Installing WordPress on Ubuntu"

---

tutorials/how-to-install-vaultwarden/01.en.md

this definitely isn't me first time writing, kindly correct my errors if needed.

how to install vaultwarden from source

---

tutorials/howto-transfer-files-using-scp/01.en.md

Signed-off-by: pixia1234 [pixia2005@gmail.com](mailto:pixia2005@gmail.com)

New tutorial "How to transfer files using scp command" 

---

tutorials/load-balancer-blue-green-deployments/01.en.md

Signed-off-by: Andy Preston andy@andyp.dev

New tutorial: Blue/Green deployments with Hetzner load balancer

---

tutorials/firewall-using-nftables/01.en.md

Signed-off-by: Tuxifan <tuxifan@posteo.de>

"Easily managing your Firewall using nftables" Tutorial

---

tutorials/how-to-set-up-nat-for-cloud-networks/01.de.md
tutorials/how-to-set-up-nat-for-cloud-networks/01.en.md

Add cloud-init script in "How to set up NAT gateway for private Cloud Networks"

---

tutorials/install-and-configure-nextcloud-collabora-online/01.de.md
tutorials/install-and-configure-nextcloud-collabora-online/01.en.md

Fix link in "Install and Configure Nextcloud Office"

---

tutorials/ai-chatbot-with-ollama-and-open-webui/01.de.md
tutorials/ai-chatbot-with-ollama-and-open-webui/01.en.md

Fix file name in "Hosting an AI chatbot with Ollama and Open WebUI"

---

tutorials/install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption-with-clevis-and-tang/01.en.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md

Update Ubuntu version in "Install an encrypted Ubuntu"

---

tutorials/cloudflare-website-protect/01.en.md

Use the suggested fix from the issue #839.

Minor change in "How to protect a website with Cloudflare without exposing ports to the Internet"

---

tutorials/install-and-configure-proxmox_ve/01.de.md
tutorials/install-and-configure-proxmox_ve/01.en.md

This is a Hetzner-internal rework of the official tutorial made by A. Riedel and M. Kitanov. I am one of the authors of this article and wanted to fix some minor issues.

rework Proxmox VE Tutorial

---

tutorials/run-docker-containers-on-a-managed-server-with-udocker/01.en.md

I've updated the udocker tutorial as announced in https://github.com/hetzneronline/community-content/issues/841

Update udocker tutorial

---

tutorials/postfix-as-SMTP-relay-server/01.en.md

Fix typo in "Postfix SMTP relay server"

---

tutorials/custom-os-images-with-packer/01.en.md

Fix typo in "Building preconfigured OS images with HashiCorp Packer"

---

tutorials/kubernetes-on-hetzner-with-cluster-api/01.de.md
tutorials/kubernetes-on-hetzner-with-cluster-api/01.en.md

I have read and understood the Contributor's Certificate of Origin available at the end of https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Lucas Rattz <lucasrattz999@gmail.com>

Managing Kubernetes on Hetzner with Cluster API

---

tutorials/how-to-install-and-use-neovim-as-ide/01.en.md

Hi. I just finished my article for your tutorials base :)
Waiting for feedback!
Signed-off-by: Karol Sarbiewski 1129032p10@gmail.com

NeoVim tutorial

---

tutorials/install-and-configure-borgmatic/01.en.md

Update for Borgmatic >=1.8
I have read and understood the Contributor's Certificate of Origin available at the end of https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md and I hereby certify that I meet the contribution criteria described in it. Signed-off-by: KagetaneHiruko

Update to "Install and configure borgmatic"

---

tutorials/howto-hcloud-ansible/01.en.md

🔄 Update "How-to: Hetzner Cloud Ansible modules"

---

tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks/01.en.md

🔄 Update "How to route cloud server over private network using pfSense and Hetzner Cloud Networks"

---

tutorials/kubernetes-on-hetzner-with-cluster-api/01.de.md
tutorials/kubernetes-on-hetzner-with-cluster-api/01.en.md

📝 Add 'update secret reference in deployment' in "Managing Kubernetes on Hetzner with Cluster API"

---

tutorials/setup-your-own-scalable-kubernetes-cluster/01.en.md

📝 Add step about Load Balancer in "Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud"

---

tutorials/analyze-nginx-access-log-using-sql/01.en.md

New tutorial - "Analyze nginx access log using SQL"

---

tutorials/install-and-configure-borgmatic/01.en.md

- Correct Typo in BorgMatic installation documentation

Correct BorgMatic documentation

---

tutorials/how-to-install-git-on-ubuntu-18.04/01.en.md
tutorials/how-to-install-git-on-ubuntu/01.en.md

🔄 Update "How To Install Git on Ubuntu"

---

tutorials/how-to-set-up-nat-for-cloud-networks/01.de.md
tutorials/how-to-set-up-nat-for-cloud-networks/01.en.md

📝 Add Ubuntu 24.04 in cloud-init in "How to set up NAT gateway for private Cloud Networks"

---

tutorials/add-ssh-key-to-your-hetzner-cloud/01.en.md

🔄 Update "How to login to your Hetzner instance with an SSH Key"

---

tutorials/how-to-set-up-nat-for-cloud-networks/01.de.md
tutorials/how-to-set-up-nat-for-cloud-networks/01.en.md

📝 Add hint in "How to set up NAT gateway for private Cloud Networks"

---

tutorials/debian-10-docker-install-dualstack-ipv6nat-firewall/01.en.md
tutorials/debian-docker-install-dualstack-firewall/01.en.md

🔄 Update "Install Docker CE on Debian 10 with Dual stack IPv6-NAT and Firewall Support"

---

tutorials/install-and-configure-danted-proxy-socks5/01.en.md

Update "Install and Configure Dante Socks5 Proxy on Debian/Ubuntu"

---

tutorials/letsencrypt-dns/01.en.md

Update "DNS Validated Let's Encrypt Certificates"

---

tutorials/jitsi-meet-on-debian-ubuntu/01.en.md

Update "Install Jitsi Meet on Debian/Ubuntu"

---

tutorials/deploy-elk-stack-with-docker/01.en.md

Signed-off-by: Ferdinand Gassauer <f.gassauer@chricar.at>

implement security measures  due to docker issues

---

tutorials/install-and-configure-nextcloud-collabora-online/01.de.md
tutorials/install-and-configure-nextcloud-collabora-online/01.en.md

Update "Install and Configure Nextcloud Office"

---

tutorials/install-caprover/01.en.md

Improve verbiage and clarity. Was the original author of the tutorial 3 years ago and there have been some things I've been wanting to change.
Signed-off-by: Mia Pigal <kedas@yarn.network>

Update install-caprover tutorial

---

tutorials/how-to-install-gitea-on-debian/01.en.md
tutorials/how-to-install-minio-on-debian/01.en.md

Signed-off-by: Mohsen Nasiri info@m0h53n.ir

Add tutorial "How to Install MinIO on Debian" And "How to Install Gitea on Debian"

---

tutorials/ssh-firewall/01.en.md

I'm not sure what the cta metadata means and I didn't find any documentation for it. But "cloud" seems to be ok. 🤷‍♂️ 
Signed-off-by: Moritz Höppner <moritz.hoeppner2@gmail.com>

New tutorial - "How to SSH without exposing your server to the internet"

---

tutorials/kubernetes-with-claudie/01.en.md

This PR updates Kubernetes with Claudie tutorial based on the description in the https://github.com/hetzneronline/community-content/issues/957

update kubernetes with Claudie tutorial

---

tutorials/howto-ssh-key/01.de.md
tutorials/howto-ssh-key/01.en.md

Add note in "Setting up an SSH key"

---

tutorials/how-to-set-up-vaultwarden/01.en.md

Update "How to set up Vaultwarden"

---

tutorials/install-nomad-consul-cluster/01.en.md

🔄 Update "Install a Nomad cluster with Consul on cloud servers"

---

tutorials/proxmox-on-cloud/01.en.md

Readd tutorial - "Proxmox on Hetzner Cloud"

---

tutorials/nextcloud-hetzner-object-storage/01.en.md

Fix typo in "Setup Nextcloud with S3-compatible object storage"

---

tutorials/install-and-configure-nextcloud/01.en.md

Updated from cx11 to cx22 server type and ubuntu from 20.04 to 24.04

Update nextcloud tutorial

---

tutorials/game-server-factorio/01.en.md

add whitespace to properly close table

---

tutorials/object-storage-based-filesystem/01.de.md
tutorials/object-storage-based-filesystem/01.en.md

Signed-off-by: DasCanard [mail@richy.sh]

added object-storage-based-filesystem tutorial 

---

tutorials/howto-setup-gitlab-ci-auto-scaling-infrastructure/01.en.md

Import tutorial from https://gitlab.com/hetznercloud/fleeting-plugin-hetzner/-/blob/39a6a36e35c172f6bf48a65746ab72e3e29bbae3/docs/tutorials/setup-gitlab-ci-test-infrastructure-from-scratch.md

Tutorial on how to Setup a GitLab CI auto scaling infrastructure

---

tutorials/run-django-app-on-webhosting-or-managed-server/01.en.md
tutorials/run-flask-app-on-webhosting-or-managed-server/01.en.md

I discovered and fixed 3 issues in my tutorials

Fix issues in flask and django tutorials

---

tutorials/install-shopware-6/01.en.md

Apply the changes suggested in #981
-------
Signed-off-by: Svenja Michal

Update tutorial - "Installation and configuration of Shopware 6"

---

tutorials/deploy-your-flask-application-using-uwsgi/01.en.md

After doing some work, I created this guide on how to deploy your Flask application. I tried to make this easy to follow.
Signed-off-by: Einar de Baas djpanther78@zohomail.eu

✨New Guide - "deploy-your-flask-application-using-uwsgi"

---

tutorials/how-to-set-up-nat-for-cloud-networks/01.de.md
tutorials/how-to-set-up-nat-for-cloud-networks/01.en.md

Fix "How to set up NAT gateway for private Cloud Networks"

---

tutorials/install-nomad-consul-cluster/01.en.md

Fix phrasing in "Install a Nomad cluster with Consul on cloud servers"

---

tutorials/install-windows/01.de.md
tutorials/install-windows/01.en.md

Fix "Installing Windows without KVM"

---

tutorials/install-debian-11-with-lvm-encrypted-nvme-software-raid/01.en.md

Add note in "How to install Debian 11 encrypted with LVM on a NVMe software RAID"

---

tutorials/install-and-configure-wireguard-vpn/01.en.md

Replace python with bash, which is more appropriate here. Works the same.

Update "Installing and configuring WireGuard VPN on Ubuntu"

---

tutorials/backupserver-with-borg/01.en.md

Fixes issue with 'borg compact' command and corrects typos

Fix: borg compact & Typo #1061

---

tutorials/obfuscating-wireguard-using-wstunnel/01.en.md

Update "Obfuscating WireGuard using Wstunnel"

---

tutorials/run-docker-containers-on-a-managed-server-with-udocker/01.en.md

I've updated the udocker tutorial and added a easy option for installation with pip

Update udocker managed server tutorial

---

tutorials/howto-linux-mount/01.de.md
tutorials/howto-linux-mount/01.en.md

Update "Linux: Formatting and mounting a block storage device"

---

tutorials/custom-os-images-with-packer/01.de.md
tutorials/custom-os-images-with-packer/01.en.md

Update "Building preconfigured OS images with HashiCorp Packer"

---

tutorials/setup-your-own-scalable-kubernetes-cluster/01.en.md

<br>
---------
<br>
Fix #943  
Fix #1017

Update "Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud"

---

tutorials/setup-monitoring-on-managed-server/01.en.md
tutorials/setup-monitoring-on-managed-server/01.ru.md

Update tutorial setup-monitoring-on-managed-server

---

tutorials/securing-ssh/01.de.md
tutorials/securing-ssh/01.en.md

Fix suggested app in "Securing the SSH service"

---

tutorials/basic-cloud-config/01.de.md
tutorials/basic-cloud-config/01.en.md

Add section about port in "Basic Cloud Config"

---

tutorials/deploy-nextjs-on-a-managed-server/01.de.md
tutorials/deploy-nextjs-on-a-managed-server/01.en.md

Signed-off-by: just-read-the-instructions <markus@imperius.cloud>

New tutorial - Deploy Next.js on a Managed Server

---

tutorials/check-and-change-hostname-on-debian/01.en.md

Minor change in "Check and change hostname on Debian"

---

tutorials/add-ssh-key-to-your-hetzner-cloud/01.en.md

📝 Add step in "How to login to your Hetzner instance with an SSH Key"

---

tutorials/security-ubuntu-settings-firewall-tools/01.de.md
tutorials/security-ubuntu-settings-firewall-tools/01.en.md

Small fix in "How to Keep Your Ubuntu Server Safe"

---

tutorials/setup-your-own-scalable-kubernetes-cluster/01.en.md

Add TLS/SSL certificate in "Setup your own scalable Kubernetes cluster with the Terraform provider for Hetzner Cloud"

---

tutorials/deploy-fastapi-on-a-hetzner-server-using-disco/01.en.md
tutorials/deploy-fastapi-on-a-server-using-disco/01.en.md

Signed-off-by: Greg Sadetsky <lepetitg@gmail.com>

FastAPI Disco Tutorial

---

tutorials/install-and-configure-proxmox_ve/01.de.md
tutorials/install-and-configure-proxmox_ve/01.en.md

Update "Install and Configure Proxmox VE"

---

tutorials/install-ubuntu-2004-with-full-disk-encryption/01.de.md
tutorials/install-ubuntu-2004-with-full-disk-encryption/01.en.md

-------------
Fix #1142 
Fix #1143

Update "How to install Ubuntu 24.04 with full disk encryption"

---

tutorials/install-outline-vpn-server/01.ru.md
tutorials/kubernetes-on-hetzner-with-crio-flannel-and-hetzner-balancer/01.ru.md

Scripts that can be useful:
1. [Extract links from Markdown files](https://github.com/wpdevelopment11/linkextr).
2. [Find the broken links using a real browser](https://github.com/wpdevelopment11/brittle).

Fix broken links

---

tutorials/securing-ssh/01.de.md
tutorials/securing-ssh/01.en.md

Update 01.en.md according to security recommendations
https://github.com/hetzneronline/community-content/issues/1177
Signed-off-by: Aeneas Tews aeneas.tews@tum.de

Update 01.en.md according to issue: #1177

---

tutorials/basic-cloud-config/01.de.md
tutorials/basic-cloud-config/01.en.md

Change file in "Basic Cloud Config"

---

tutorials/run-wordpress-in-a-container-using-docker-compose/01.en.md

Add a missing link

---

tutorials/deploy-elk-stack-with-docker/01.en.md

Remove extra space in "Deploy your own ELK stack using Docker Compose"

---

tutorials/Get-Drupal-in-your-webhosting/01.de.md
tutorials/Get-Drupal-in-your-webhosting/02.en.md
tutorials/How-to-install-Shopware-in-your-Hetzner-Webosting/01.de.md
tutorials/How-to-install-Shopware-in-your-Hetzner-Webosting/02.en.md
tutorials/add-opencart-to-your-hetzner-web-hosting/01.de.md
tutorials/add-opencart-to-your-hetzner-web-hosting/02.en.md
tutorials/how-to-implement-Contao-in-your-Webhosting/01.de.md
tutorials/how-to-implement-Contao-in-your-Webhosting/02.en.md
tutorials/how-to-install-Joomla-in-your-browser/01.de.md
tutorials/how-to-install-Joomla-in-your-browser/02.en.md
tutorials/how-to-install-wordpress-on-hetzner-web-hosting/01.de.md
tutorials/how-to-install-wordpress-on-hetzner-web-hosting/01.en.md

Fix formatting in:
* [Get-Drupal-in-your-webhosting](https://github.com/hetzneronline/community-content/tree/master/tutorials/Get-Drupal-in-your-webhosting)
* [How-to-install-Shopware-in-your-Hetzner-Webosting](https://github.com/hetzneronline/community-content/tree/master/tutorials/How-to-install-Shopware-in-your-Hetzner-Webosting)
* [add-opencart-to-your-hetzner-web-hosting](https://github.com/hetzneronline/community-content/tree/master/tutorials/add-opencart-to-your-hetzner-web-hosting)
* [how-to-implement-Contao-in-your-Webhosting](https://github.com/hetzneronline/community-content/tree/master/tutorials/how-to-implement-Contao-in-your-Webhosting)
* [how-to-install-Joomla-in-your-browser](https://github.com/hetzneronline/community-content/tree/master/tutorials/how-to-install-Joomla-in-y …

Fix formatting in webhosting tutorials

---

tutorials/resize-root-and-create-data-partition/01.en.md

Hello, I wanted to find a way to resize my root partition and create a new data partition, but I didnt found any documentation and its a hard topic, so I decided to create a tutorial. 
Signed-off-by: Max Witt [me@max-witt.de](mailto:me@max-witt.de)

Create Tutorial: "resizing root and data partition"

---

tutorials/how-to-install-oxid-hetzner-webhosting/01.de.md
tutorials/how-to-install-oxid-hetzner-webhosting/01.en.md

Signed-off-by: Dominik Poß dominik.poss@hetzner.com / atmidian@gmail.com

Add tutorial for Oxid for Webhosting/Managed Server
